# Puerto del servidor
quarkus.http.port=8080

# Configuración de base de datos PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/truck_rental
quarkus.datasource.db-version=15.9.0
# Enable logging of SQL statements
quarkus.hibernate-orm.log.sql=true

# Optional: Format the SQL for better readability
quarkus.hibernate-orm.log.format-sql=true

# Optional: Log the bind parameter values (requires TRACE log level for org.hibernate.type.descriptor.sql)
quarkus.hibernate-orm.log.bind-params=true

# Hibernate ORM
# validate: verifica que el esquema coincida (recomendado cuando la tabla ya existe)
# quarkus.hibernate-orm.schema-management.strategy=validate

# ejecucion: con un jdk personalizado y maven personalizado
#JAVA_HOME="/Users/gustavo/Documents/instaladores/jdk-19.0.2.jdk/Contents/Home"
# "/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/mvn" quarkus:dev -Ddebug

# ejecucion directa con maven (hay que tener instalado maven y en el PATH)
#mvn quarkus:dev -Ddebug
